name: Build and deploy ASP.Net Core app to Azure Web App

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./UnitTests
      - name: Execute unit tests
        run: dotnet test
        working-directory: ./UnitTests
