/*
 * System rezerwacji miejsc na eventy
 *
 * Niniejsza dokumentacja stanowi opis REST API implemtowanego przez serwer centralny. Endpointy 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: XXX@pw.edu.pl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace biletmajster_backend.Domain.DTOS
{ 
        /// <summary>
        /// event status
        /// </summary>
        /// <value>event status</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum EventStatusDTO
        {
            /// <summary>
            /// Enum InFutureEnum for inFuture
            /// </summary>
            [EnumMember(Value = "inFuture")]
            InFutureEnum = 0,
            /// <summary>
            /// Enum PendingEnum for pending
            /// </summary>
            [EnumMember(Value = "pending")]
            PendingEnum = 1,
            /// <summary>
            /// Enum DoneEnum for done
            /// </summary>
            [EnumMember(Value = "done")]
            DoneEnum = 2,
            /// <summary>
            /// Enum CancelledEnum for cancelled
            /// </summary>
            [EnumMember(Value = "cancelled")]
            CancelledEnum = 3        }
}
